### ISSUE TITLE
Time zone aware schedules

### ISSUE THREAD

**Issue by kfh** [InsanusMokrassar/krontab#14]
First of all, this looks like a really useful library that fits nicely into the current project i'm working on. 

One of my needs is to have schedules on specific days in different time zones.  I can't see anywhere to configure the time zone for the current schedule, isn't this supported as of now? If not, i see you are using the _Klock library_ after a quick poke into the codebase. Klock supports _time zone offsets_, isn't it possible to use this feature?

**Comment by InsanusMokrassar** [comment]
Hello, thanks for your feedback:)

Yes, as I know, it is available in Klock out of the box and I will try hard to include opportunity to set it up as soon as possible

**Comment by InsanusMokrassar** [comment]
Hello, @kfh , I have implemented work with time zoned date time #16 , but I am not pretty sure that it is exactly what you have meant in this issue:) anyway, you may take a look this PR and maybe give some suggestions

**Comment by kfh** [comment]
> Hello, @kfh , I have implemented work with time zoned date time #16 , but I am not pretty sure that it is exactly what you have meant in this issue:) anyway, you may take a look this PR and maybe give some suggestions

Thanx for the effort! Maybe i wasn't too clear, but what i'm looking for is a way to run ie a schedule on _every monday at 09:00 in a given timezone(ie "Europe/Berlin")_ so that we are independent of where the code is running(Cloud in a given region etc). I think it would make sens to offer a _thin convenience layer_ on top of the _Klock API_ so that one could just pass in _timezone strings_ which then would be _converted to offsets_ behind the scenes. I'm thinking someting along the lines of what they are doing in [kotlinx-datetime](https://github.com/Kotlin/kotlinx-datetime#converting-an-instant-to-local-date-and-time-components).

**Comment by InsanusMokrassar** [comment]
The problem is that you will be able to use it only with `DateTimeTz`, because of simple `DateTime` have no any time zone variant and in fact may be used only as `utc` analog. I think, I can add an option in `krontab` string and builder, but it will work only with `next(DateTimeTz)` avariant of `next` method

**Comment by kfh** [comment]
> The problem is that you will be able to use it only with `DateTimeTz`, because of simple `DateTime` have no any time zone variant and in fact may be used only as `utc` analog. I think, I can add an option in `krontab` string and builder, but it will work only with `next(DateTimeTz)` avariant of `next` method

There are of course cases where the _timezone is insignificant_, ie when a schedule is based on running every 5 minutes or every hour or so. I guess this could be solved in different ways internally, ie using _ DateTimeTz_ everywhere and just using the default when the time zone is not relevant, it probably _defaults to UTC time_ anyways. The important bit is that one has the possibility to pass in the time zone when it matters and that the underlying code handles this case properly.

**Comment by InsanusMokrassar** [comment]
Hello:) i have included minutes offset into string parsing and you may test it if you will include artifacts from github packages of this repository

**Comment by InsanusMokrassar** [comment]
This is my answer for [this comment](https://github.com/InsanusMokrassar/krontab/pull/16#discussion_r605630027)

1. `DateTime.now()` will return object with current system locale date and time. So, you can pass this object to `next` method and get next time relatively to system locale
2. Now there is opportunity to use offset part. This part will works ONLY in `next(DateTimeTz)` method

If to be honest, currently I am not pretty sure how should we made including an offset in config due to the fact that it will not work with `DateTime` if you are not passing and offset parameter

Of course, you are welcome with some with PullRequest with you point of view for this issue

**Comment by kfh** [comment]
> This is my answer for [this comment](https://github.com/InsanusMokrassar/krontab/pull/16#discussion_r605630027)
> 
> 1. `DateTime.now()` will return object with current system locale date and time. So, you can pass this object to `next` method and get next time relatively to system locale
> 2. Now there is opportunity to use offset part. This part will works ONLY in `next(DateTimeTz)` method
> 
> If to be honest, currently I am not pretty sure how should we made including an offset in config due to the fact that it will not work with `DateTime` if you are not passing an offset parameter
> 

My suggestion was that you use _DateTimeTz_ everywhere to make the api cleaner. It would probably mean that you have to rewrite some code i guess. If the next() method signature is something like the following:

`suspend fun next(relatively: DateTimeTz = DateTime.now().utc): DateTimeTz?` 

shouldn't that cover all cases? When the time zone is not relevant, ie when a schedule runs every minute, the time zone doesn't matter anyway, right. So it's not significant that it's utc based. And when you actually want to adjust the time zone that also works as you have done in the pull request.  

> Of course, you are welcome with some with PullRequest with your point of view for this issue

Noted! :)

**Comment by InsanusMokrassar** [comment]
I see your point:) Anyway, currently I am still thinking about how to implement it in the most comfortable way

**Comment by InsanusMokrassar** [comment]
> > This is my answer for [this comment](https://github.com/InsanusMokrassar/krontab/pull/16#discussion_r605630027)
> > 
> > 1. `DateTime.now()` will return object with current system locale date and time. So, you can pass this object to `next` method and get next time relatively to system locale
> > 2. Now there is opportunity to use offset part. This part will works ONLY in `next(DateTimeTz)` method
> > 
> > If to be honest, currently I am not pretty sure how should we made including an offset in config due to the fact that it will not work with `DateTime` if you are not passing an offset parameter
> 
> My suggestion was that you use _DateTimeTz_ everywhere to make the api cleaner. It would probably mean that you have to rewrite some code i guess. If the next() method signature is something like the following:
> 
> `suspend fun next(relatively: DateTimeTz = DateTime.now().utc): DateTimeTz?`
> 
> shouldn't that cover all cases? When the time zone is not relevant, ie when a schedule runs every minute, the time zone doesn't matter anyway, right. So it's not significant that it's utc based. And when you actually want to adjust the time zone that also works as you have done in the pull request.
> 
> > Of course, you are welcome with some with PullRequest with your point of view for this issue
> 
> Noted! :)

There are two options about solving of offset problem:

1. Simple. We are just adding timezoned `DateTimeTz` and pass offset via some parameter like `offset: Minutes` in methods like `buildSchedule`/`createSimpleScheduler`/etc.
2. Difficult (as solved for now). We are adding option to parsing and get opportunity to serialize/deserialize and save/load configuration for each string-oriented `KronScheduler`

If you see any other option about realization, I would be glad to hear it. Anyway, both ways in the options above were included. Currently I am thinking about default realization for method `next(DateTimeTz)`, because of it is not very obvious what woulb be better to get as default way - we are assuming that method `KronScheduler#next(DateTime)` usually called in `utc` offset or `local`

**Comment by InsanusMokrassar** [comment]
@kfh hello, now you can checkout new version with time zones and weekdays :)
